# Generated by Django 4.2.30 on 2026-05-30 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Acceptée', "Acceptée par l'enseignant"), ('Refusée', "Refusée par l'enseignant"), ('Validée', 'Validée définitivement'), ('Archivée', 'Archivée')], default='En attente', max_length=20)),
                ('cv', models.FileField(upload_to='cvs/%Y/%m/')),
                ('lettre_motivation', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Demande de Stage',
                'verbose_name_plural': 'Demandes de Stage',
                'db_table': 'DemandeStage',
            },
        ),
        migrations.CreateModel(
            name='PropositionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('technologies', models.CharField(blank=True, help_text='Ex: Django, React, MySQL', max_length=255, null=True)),
                ('entreprise', models.CharField(max_length=150)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(default='Ouvert', max_length=50)),
            ],
            options={
                'verbose_name': 'Proposition de Stage',
                'verbose_name_plural': 'Propositions de Stage',
                'db_table': 'PropositionStage',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('etudiant', 'Étudiant'), ('enseignant', 'Enseignant'), ('admin', 'Administrateur')], max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'Utilisateur',
            },
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stages.utilisateur')),
                ('grade', models.CharField(max_length=100)),
                ('departement', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
                'db_table': 'Enseignant',
            },
            bases=('stages.utilisateur',),
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stages.utilisateur')),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('specialite', models.CharField(max_length=100)),
                ('niveau', models.CharField(max_length=50)),
                ('departement', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
                'db_table': 'Etudiant',
            },
            bases=('stages.utilisateur',),
        ),
        migrations.CreateModel(
            name='Refus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField()),
                ('date_refus', models.DateTimeField(auto_now_add=True)),
                ('demande', models.OneToOneField(db_column='id_demande', on_delete=django.db.models.deletion.CASCADE, related_name='details_refus', to='stages.demandestage')),
            ],
            options={
                'verbose_name': 'Refus',
                'verbose_name_plural': 'Refus',
                'db_table': 'Refus',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('utilisateur', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='stages.utilisateur')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'Notification',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.AddField(
            model_name='demandestage',
            name='proposition',
            field=models.ForeignKey(db_column='id_proposition', on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='stages.propositionstage'),
        ),
        migrations.CreateModel(
            name='Attestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100, unique=True)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('fichier_pdf', models.FileField(upload_to='attestations/%Y/')),
                ('appreciation', models.TextField(blank=True, null=True)),
                ('mention', models.CharField(blank=True, max_length=50, null=True)),
                ('demande', models.OneToOneField(db_column='id_demande', on_delete=django.db.models.deletion.CASCADE, related_name='attestation', to='stages.demandestage')),
            ],
            options={
                'verbose_name': 'Attestation',
                'verbose_name_plural': 'Attestations',
                'db_table': 'Attestation',
            },
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_archivage', models.DateTimeField(auto_now_add=True)),
                ('demande', models.OneToOneField(db_column='id_demande', on_delete=django.db.models.deletion.CASCADE, related_name='archive', to='stages.demandestage')),
            ],
            options={
                'verbose_name': 'Archive',
                'verbose_name_plural': 'Archives',
                'db_table': 'Archive',
            },
        ),
        migrations.AddField(
            model_name='propositionstage',
            name='enseignant',
            field=models.ForeignKey(db_column='id_enseignant', on_delete=django.db.models.deletion.RESTRICT, related_name='propositions', to='stages.enseignant'),
        ),
        migrations.AddField(
            model_name='demandestage',
            name='etudiant',
            field=models.ForeignKey(db_column='id_etudiant', on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='stages.etudiant'),
        ),
    ]
